module Trophy
  module Configurable
    extend ActiveSupport::Concern

    # 達成条件
    PLAN_COUNT_LV1_THRESHOLD    = 10
    PLAN_COUNT_LV2_THRESHOLD    = 30
    PLAN_COUNT_LV3_THRESHOLD    = 50
    PLAN_COUNT_LV4_THRESHOLD    = 100
    PV_COUNT_LV1_THRESHOLD      = 1_000
    PV_COUNT_LV2_THRESHOLD      = 10_000
    PV_COUNT_LV3_THRESHOLD      = 100_000
    PV_COUNT_LV4_THRESHOLD      = 1_000_000
    LIKE_COUNT_LV1_THRESHOLD    = 50
    LIKE_COUNT_LV2_THRESHOLD    = 100
    LIKE_COUNT_LV3_THRESHOLD    = 1_000
    LIKE_COUNT_LV4_THRESHOLD    = 5_000
    COMMENT_COUNT_LV1_THRESHOLD = 10
    COMMENT_COUNT_LV2_THRESHOLD = 50
    COMMENT_COUNT_LV3_THRESHOLD = 100
    COMMENT_COUNT_LV4_THRESHOLD = 500
  end
end
