development:
  securityGroupIds:
    - xxxxxx
  subnetIds:
    - yyyyyy
    - zzzzzz

production:
  securityGroupIds:
    - sg-019f9354fb7e44c9b
  subnetIds:
    - subnet-0158ed0b38cf7e42a
    - subnet-041ffda5180322c7e
